//
// Specific Neighborhood
//

export const neighbourhoodData = {
  Business_Bay: {
    backgroundImage: "/images/BusinessBayBg.jpg",
    neighbourhood: "Business Bay",
    WelcomeDesc: `Straddling Dubai Creek, Business Bay is a contemporary financial district packed with corporate high-rises, stylish apartments buildings, and swanky hotels. Dubai Water Canal has jogging and cycling tracks plus a colorful mechanical waterfall. Mid-priced stores fill Bay Avenue mall, along with family-friendly dining options. Smart waterside restaurants serve Lebanese dishes, Asian street snacks, and high-end seafood.`,
    expectWhatDesc:
      "A contemporary, futuristic and manageable neighborhood easy to commute.",
    marketDesc:
      "Mid end to high end, mostly high rise building with stunning views.",
    loveThingsDesc:
      "Relaxing strolls along the waterfront, outdoor activities, dining and lounging.",
    map: "/images/businessBayMap.png",
    neighbours: {
      north: "Sheikh Zayed Road",
      west: "Al Khail Road",
      south: "Downtown Dubai",
      east: "Al Qouz",
    },
    dxbairport: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: 233,
    },
    dwcairport: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: null,
    },
    publicbeach: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: 233,
    },
    dubaimall: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: 233,
    },
    expo2020: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: null,
    },
    dubaimarina: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: 233,
    },
    aroundTheBlockDesc: `Business Bay is Dubai’s main business district covering an area of 5,9 million m2 or 64 million square feet. It is diverted in a southeast and a northwest part by the Dubai Canal. The masterplan was developed 2003 by Dubai Properties, one of Dubai’s large government developers. As more and more buildings get completed and empty plots disappear Business Bay becomes a lively business and residential district. Its excellent location within Dubai makes it the place to be for more than 15 luxurious 5-star hotels and over 20 4-star hotels.`,
    aroundTheBlockImages: [
      "/images/aroundTheBlock/around1.jpg",
      "/images/aroundTheBlock/around2.jpg",
      "/images/aroundTheBlock/around3.jpg",
      "/images/aroundTheBlock/around4.jpg",
    ],
    whatToExpectDesc: `Even so Business Bay is the pulsating business heart of Dubai, it is not a noisy place compared to other major cities. Business Bay offers stunning views from almost every angle, a waterfront life, small parks and countless options for dining on every level. For sport enthusiasts, there are multiple running and cycling tracks which relate to Dubai’s vast cycling track network of more than 500 km.`,
    whatToExpectImages: [
      "/images/whatToExpect/expect1.jpg",
      "/images/whatToExpect/expect2.jpg",
      "/images/whatToExpect/expect3.jpg",
      "/images/whatToExpect/expect4.jpg",
      "/images/whatToExpect/expect5.jpg",
      "/images/whatToExpect/expect6.jpg",
      "/images/whatToExpect/expect7.jpg",
      "/images/whatToExpect/expect8.jpg",
      "/images/whatToExpect/expect9.jpg",
      "/images/whatToExpect/expect10.jpg",
      "/images/whatToExpect/expect11.jpg",
    ],
    theMarketDesc: `Super high end, high rise residential buildings like “The Volante” are also available as mid end residential complexes like the “Executive Towers” with almost 1,800 apartments in 10 towers. Some of the worlds most renowned architects like Zaha Hadid with her “The Opus” tower or the JW Marriott Hotel Towers, the second highest twin towers in the world designed by Ashok Korgaonkar amongst many others formed Business Bay into one of the most beautiful business districts in the world.`,
    theMarketImages: [
      "/images/theMarket/market1.jpg",
      "/images/theMarket/market2.jpg",
      "/images/theMarket/market3.jpg",
      "/images/theMarket/market4.jpg",
      "/images/theMarket/market5.jpg",
      "/images/theMarket/market6.jpg",
    ],
    thingsToLoveDesc: `Business Bay is a multicultural hub for all nationalities with endless options for dining, clubbing or just to hang out with friends enjoying a drink. Spectacular roof top bars with truly breathtaking views (and similar prices) can also be found like restaurants where you can feed a family with just 50 Dirhams. Depending on where you live in Business Bay, Dubai Mall with all its entertainment options is just a short walk or a short ride away.`,
    thingsToLoveImages: [
      "/images/thingsToLove/things1.jpg",
      "/images/thingsToLove/things2.jpg",
      "/images/thingsToLove/things3.jpg",
      "/images/thingsToLove/things4.jpg",
      "/images/thingsToLove/things5.jpg",
      "/images/thingsToLove/things6.jpg",
      "/images/thingsToLove/things7.jpg",
      "/images/thingsToLove/things8.jpg",
      "/images/thingsToLove/things9.jpg",
    ],
  },
  Downtown_Dubai: {
    backgroundImage: "/images/DowntownDubaiBg.jpg",
    neighbourhood: "Downtown Dubai",
    WelcomeDesc: `Downtown is the 2 square kilometer pulsating heart of Dubai with plenty of wow-factors for residents and tourists alike. Pedestrian friendly designed with wide promenades, Downtown Dubai invites visitors and residents for strolls along Sheikh Mohammed bin Rashid Boulevard with its countless and irresistible restaurants and cafes. Downtown is perfectly located between the city’s two largest business districts, Dubai International Financial Centre in the north and Business Bay in the south.`,
    expectWhatDesc:
      "Ultimate urban lifestyle with iconic landmarks, entertainment and glamour.",
    marketDesc:
      "Simply one of the most prestigious and splendid neighborhoods on earth.",
    loveThingsDesc:
      "Phenomenal architecture, world-class shopping and beautiful promenades.",
    map: "/images/businessBayMap.png",
    neighbours: {
      north: "Al Asayel Road",
      west: "Sheikh Zayed Road",
      south: "Burj Khalifa Boulevard",
      east: "Financial Center Road",
    },
    dxbairport: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: 233,
    },
    dwcairport: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: null,
    },
    publicbeach: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: 233,
    },
    dubaimall: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: 233,
    },
    expo2020: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: null,
    },
    dubaimarina: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: 233,
    },
    aroundTheBlockDesc: `Downtown is the 2 square kilometer pulsating heart of Dubai with plenty of wow-factors for residents and tourists alike. Pedestrian friendly designed with wide promenades, Downtown Dubai invite visitors and residents for strolls along Sheikh Mohammed bin Rashid Boulevard with its countless and irresistible restaurants and cafés. Downtown is perfectly located between the city’s two largest business districts, Dubai International Financial Centre in the north and Business Bay in the south.`,
    aroundTheBlockImages: [
      "/images/aroundTheBlock/around1.jpg",
      "/images/aroundTheBlock/around2.jpg",
      "/images/aroundTheBlock/around3.jpg",
      "/images/aroundTheBlock/around4.jpg",
    ],
    whatToExpectDesc: `Centerpiece in Downtown Dubai beside the Burj Khalifa is the Dubai mall, one of the world’s largest malls with 5,9 million sqft. internal floor area, which hosts more than 1,200 stores and more than 200 food and beverage outlets, an Olympic size ice rink and the famous aquarium and underwater zoo. Dubai Mall is the world's most-visited shopping and leisure destination and is attracting more than 60 million visitors a year.`,
    whatToExpectImages: [
      "/images/whatToExpect/expect1.jpg",
      "/images/whatToExpect/expect2.jpg",
      "/images/whatToExpect/expect3.jpg",
      "/images/whatToExpect/expect4.jpg",
      "/images/whatToExpect/expect5.jpg",
      "/images/whatToExpect/expect6.jpg",
      "/images/whatToExpect/expect7.jpg",
      "/images/whatToExpect/expect8.jpg",
      "/images/whatToExpect/expect9.jpg",
      "/images/whatToExpect/expect10.jpg",
      "/images/whatToExpect/expect11.jpg",
    ],
    theMarketDesc: `Downtown Dubai as one of the most prestigious and splendid neighborhoods on earth is the true centerpiece of the emirate Dubai. It is a mix of modern and traditional architecture – impressive and gleaming towers next to beautiful arabian style low rise buildings in the old town district. And there are still pockets of green to explore. Several super luxury 5-star hotels are located at Downtown Dubai and attract tourists throughout the whole year.`,
    theMarketImages: [
      "/images/theMarket/market1.jpg",
      "/images/theMarket/market2.jpg",
      "/images/theMarket/market3.jpg",
      "/images/theMarket/market4.jpg",
      "/images/theMarket/market5.jpg",
      "/images/theMarket/market6.jpg",
    ],
    thingsToLoveDesc: `Take a stroll around the man made Burj Khalifa lake with over 120,000 m2, or down the boulevard, watch the supercars driving by and take a break in one of the mouthwatering al fresco dining restaurant and café options. In the evening, when the tall palm trees are illuminated by fairy lights, the atmosphere is so special and give you the feeling that life is truly great. Watch people passing by, dressed up to the nines heading to a concert, Opera performance or other events at the Opera.`,
    thingsToLoveImages: [
      "/images/thingsToLove/things1.jpg",
      "/images/thingsToLove/things2.jpg",
      "/images/thingsToLove/things3.jpg",
      "/images/thingsToLove/things4.jpg",
      "/images/thingsToLove/things5.jpg",
      "/images/thingsToLove/things6.jpg",
      "/images/thingsToLove/things7.jpg",
      "/images/thingsToLove/things8.jpg",
      "/images/thingsToLove/things9.jpg",
    ],
  },
  Dubai_Marina: {
    backgroundImage: "/images/DowntownDubaiBg.jpg",
    neighbourhood: "Dubai Marina",
    WelcomeDesc: `Dubai Marina, built on a 3 kilometer (2 miles) long stretch of shoreline is today world’s largest man-made marina and one of the most beautiful canal cities globally. Around a central waterway with countless marina berths more than 200 towers are offering spectacular views over the Persian Gulf and the marvelous marina.`,
    expectWhatDesc:
      "A contemporary, unique canal city with multiple ultra-high-rise towers offering stunning views.",
    marketDesc:
      "More than 200 residential towers from all building classes with great access to public transportation.",
    loveThingsDesc:
      "Countless options for dining on all levels, multicultural waterfront living and easy beach access.",
    map: "/images/businessBayMap.png",
    neighbours: {
      north: "Persian Gulf",
      west: "Sheikh Zayed Road",
      south: "Jebel Ali",
      east: "Internet City",
    },
    dxbairport: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: 233,
    },
    dwcairport: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: null,
    },
    publicbeach: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: 233,
    },
    dubaimall: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: 233,
    },
    expo2020: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: null,
    },
    dubaimarina: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: 233,
    },
    aroundTheBlockDesc: `The canal with more than 8 km of landscaped public walkways is the center of the marina and occupies more than 12% of the total space. The two sea exits of the canal make part of Dubai Marina an island, including the neighboring district Jumeirah Beach Residences (JBR) which separates Dubai Marina from the sea.`,
    aroundTheBlockImages: [
      "/images/aroundTheBlock/around1.jpg",
      "/images/aroundTheBlock/around2.jpg",
      "/images/aroundTheBlock/around3.jpg",
      "/images/aroundTheBlock/around4.jpg",
    ],
    whatToExpectDesc: `Plenty of tourists strolling around in Dubai Marina mixing up with residents making Dubai Marina a bustling area with a unique flair. Seemingly conflicting architecture combines to create one of the most beautiful skylines in the city.`,
    whatToExpectImages: [
      "/images/whatToExpect/expect1.jpg",
      "/images/whatToExpect/expect2.jpg",
      "/images/whatToExpect/expect3.jpg",
      "/images/whatToExpect/expect4.jpg",
      "/images/whatToExpect/expect5.jpg",
      "/images/whatToExpect/expect6.jpg",
      "/images/whatToExpect/expect7.jpg",
      "/images/whatToExpect/expect8.jpg",
      "/images/whatToExpect/expect9.jpg",
      "/images/whatToExpect/expect10.jpg",
      "/images/whatToExpect/expect11.jpg",
    ],
    theMarketDesc: `Dubai marina is for sure one of the top residential areas in Dubai. Many residents fall in love with Dubai marina because of the unique waterfront living in this magical neighborhood. Prices for a studio start around AED 35k whereas 1-bedroom apartments are available from AED 40k to AED 100k. 2 beds start around AED 55k and top out at AED 200k. The annual rent for 3-bed apartments is between AED 80k and AED 300k. Large penthouses can cost anywhere between AED 350k and AED 1m. Apartments in Marina are generally larger in size then in other areas. Apart from apartments there are in some towers a few podium level townhouses available.`,
    theMarketImages: [
      "/images/theMarket/market1.jpg",
      "/images/theMarket/market2.jpg",
      "/images/theMarket/market3.jpg",
      "/images/theMarket/market4.jpg",
      "/images/theMarket/market5.jpg",
      "/images/theMarket/market6.jpg",
    ],
    thingsToLoveDesc: `Dubai Marina is a pedestrian friendly neighborhood with almost everything available within a walking distance. As traffic is sometimes very dense and parking options are rare, many residents prefer to use the tram. The laid back waterfront living within this with high rises packed, bustling district and the close proximity to the beach create a living experience nowhere else can be found.`,
    thingsToLoveImages: [
      "/images/thingsToLove/things1.jpg",
      "/images/thingsToLove/things2.jpg",
      "/images/thingsToLove/things3.jpg",
      "/images/thingsToLove/things4.jpg",
      "/images/thingsToLove/things5.jpg",
      "/images/thingsToLove/things6.jpg",
      "/images/thingsToLove/things7.jpg",
      "/images/thingsToLove/things8.jpg",
      "/images/thingsToLove/things9.jpg",
    ],
  },
  DIFC: {
    backgroundImage: "/images/DubaiMarinaBg.jpg",
    neighbourhood: "DIFC",
    WelcomeDesc: `Middle East’s leading financial hub is a district where business meets art and culinary excellence. As a special economic zone DIFC spans over 110 ha (272 acres) and has its own independent internationally regulated judicial and regulatory system and is home to hundreds of financial institutions, wealth funds, REIT’s and investors.`,
    expectWhatDesc:
      "A contemporary, futuristic designed financial district with an excellent infrastructure.",
    marketDesc:
      "High rise high-end office and residential buildings with spectacular architecture and stunning views.",
    loveThingsDesc:
      "An unparalleled destination for business, arts and fine dining.",
    map: "/images/businessBayMap.png",
    neighbours: {
      north: "Sheikh Zayed Road",
      west: "Al Mustaqbal Street",
      south: "Downtown Dubai",
      east: "2nd Za'abeel Road",
    },
    dxbairport: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: 233,
    },
    dwcairport: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: null,
    },
    publicbeach: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: 233,
    },
    dubaimall: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: 233,
    },
    expo2020: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: null,
    },
    dubaimarina: {
      distance: 18.7,
      car: 15,
      metro: 113,
      walking: 233,
    },
    aroundTheBlockDesc: `As one of the world’s top financial centres, DIFC is the leading financial hub in the Middle East, Africa and South Asia (MEASA) region. More than 1,000 companies are registered in the DIFC Free zone with more than 30% are so called Fintech companies. The district is governed by a common-law framework distinct from the United Arab Emirates (UAE) legal system, with laws and regulations issued in English. DIFC offers clients a 50-year guarantee of zero taxes on corporate income and profits, complemented by the UAE's network of double taxation treaties.`,
    aroundTheBlockImages: [
      "/images/aroundTheBlock/around1.jpg",
      "/images/aroundTheBlock/around2.jpg",
      "/images/aroundTheBlock/around3.jpg",
      "/images/aroundTheBlock/around4.jpg",
    ],
    whatToExpectDesc: `Iconic architecture and the mix between high end residential and ultra-modern office buildings paired with excellent infrastructure, perfect accessibility, connectivity, and the central location within Dubai make DIFC to one of the most sought-after areas across Dubai. An underground road called "the tunnel" is built for all kind of delivery or waste disposal trucks. It connects most buildings and make sure, commercial traffic is reduced to an absolute minimum.`,
    whatToExpectImages: [
      "/images/whatToExpect/expect1.jpg",
      "/images/whatToExpect/expect2.jpg",
      "/images/whatToExpect/expect3.jpg",
      "/images/whatToExpect/expect4.jpg",
      "/images/whatToExpect/expect5.jpg",
      "/images/whatToExpect/expect6.jpg",
      "/images/whatToExpect/expect7.jpg",
      "/images/whatToExpect/expect8.jpg",
      "/images/whatToExpect/expect9.jpg",
      "/images/whatToExpect/expect10.jpg",
      "/images/whatToExpect/expect11.jpg",
    ],
    theMarketDesc: `Occupancy levels in DIFC are always lower than in other areas. You can find everything from studios to luxury penthouse suites. Prices start around 60k for a studio and climb to 450k for a 5-bed penthouse, but you can find sometimes also more expensive large penthouses for above 600k. Awe-inspiring office towers with their state-of-the- art urban architecture and technology and multiple sophisticated 5-star hotels complete this amazingly unique district.`,
    theMarketImages: [
      "/images/theMarket/market1.jpg",
      "/images/theMarket/market2.jpg",
      "/images/theMarket/market3.jpg",
      "/images/theMarket/market4.jpg",
      "/images/theMarket/market5.jpg",
      "/images/theMarket/market6.jpg",
    ],
    thingsToLoveDesc: `In DIFC you can find the highest density of Michelin stared chefs in Dubai. A few of these restaurants rank among the top 50 best restaurants in the world.`,
    thingsToLoveImages: [
      "/images/thingsToLove/things1.jpg",
      "/images/thingsToLove/things2.jpg",
      "/images/thingsToLove/things3.jpg",
      "/images/thingsToLove/things4.jpg",
      "/images/thingsToLove/things5.jpg",
      "/images/thingsToLove/things6.jpg",
      "/images/thingsToLove/things7.jpg",
      "/images/thingsToLove/things8.jpg",
      "/images/thingsToLove/things9.jpg",
    ],
  },
};

//
// Specific Neighborhood
//
