export const UAEStates = [
  "All Emirates",
  "Dubai",
  "Abu Dhabi",
  "Sharjah",
  "Umm Al Quwain",
  "Fujairah",
  "Ajman",
  "Ras Al Khaimah",
];

export const UAEStateCities = {
  "All Emirates": ["All Cities"],
  "Abu Dhabi": [
    "All Cities",
    "Abu Dhabi City",
    "Abu al Abyad",
    "Al-Aryam Island",
    "Al-Bahiyah",
    "Al-Shahamah",
    "Al-Wathbah",
    "Bani Yas City",
    "Ghantoot",
    "Halat al Bahrani",
    "Jubail Island",
    "Khalifa Port",
    "Masdar City",
    "Mina' Zayed",
    "Mussafah",
    "Saadiyat Island",
    "Yas Island",
    "Madinat Zayed",
    "Ghayathi",
    "Ghuwaifat",
    "Habshan",
    "Liwa Oasis",
    "Marawah Island",
    "Ruwais",
    "Sila",
    "Sir Bani Yas",
    "Tarif",
    "Al Ain",
    "Al-Faqa'",
    "Al-Hayer",
    "Al-Qu'a",
    "Al-Shwaib",
    "Al-Wagan",
    "Al-Yahar",
    "Mezyad",
    "Nahil",
    "Remah",
    "Sa'ah",
    "Sweihan",
  ],
  Dubai: ["All Cities", "Dubai", "Jebel Ali", "Hatta"],
  Sharjah: [
    "All Cities",
    "Sharjah",
    "Khor Fakkan",
    "Kalba",
    "Dhaid",
    "Dibba Al-Hisn",
    "Al Madam",
  ],
  "Umm Al Quwain": ["Umm al-Quwain"],
  Fujairah: ["All Cities", "Fujairah", "Dibba Al-Fujairah"],
  Ajman: ["Ajman"],
  "Ras Al Khaimah": ["All Cities", "RAK City", "Ar-Rams"],
};

export const PropertyTypes = [
  "Select All",
  "Apartment",
  "Villa",
  "Townhouse",
  "Hotel Apartment",
  "Duplex Apartment",
  "Penthouse",
  "Lots/Land",
  "Manufactured",
];
